# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:12.7
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: bpc_rails_demo_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:password@localhost:5432/bpc_rails_demo_test"
      PG_DATABASE: bpc_rails_demo_test
      PG_HOST: localhost
      PG_USER: postgres
      PG_PASSWORD: password
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        # https://github.com/ruby/setup-ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install PostgreSQL 12 client
        run: |
          sudo apt-get -yqq install libpq-dev
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:setup
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake

  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        # https://github.com/ruby/setup-ruby
        uses: ruby/setup-ruby@v1        
        with:
          bundler-cache: true
      # Add or replace any other lints here
      - name: Security audit dependencies
        run: bin/bundler-audit --update
      - name: Security audit application code
        run: bin/brakeman -q -w2
      - name: Lint Ruby files
        run: bin/rubocop --parallel
