#################################################################
# default
#################################################################
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

#################################################################
# development
#################################################################
development:
  <<: *default
  database: bpc_rails_demo_development

  # Connect on a TCP socket
  host: localhost
  username: postgres
  password: password

#################################################################
# test
#################################################################
test:
  <<: *default
  database: <%= ENV.fetch('PG_DATABASE', 'bpc_rails_demo_test') %> 
  host:     <%= ENV.fetch('PG_HOST',  'localhost') %>
  username: <%= ENV.fetch('PG_USER', 'postgres') %>
  password: <%= ENV.fetch('PG_PASSWORD', 'password') %>
  port:     <%= ENV.fetch('PG_PORT', 5432) %>

#################################################################
# production
#################################################################
production:
  <<: *default
  database: bpc_rails_demo_production
  username: bpc_rails_demo
  password: <%= ENV["BPC_RAILS_DEMO_DATABASE_PASSWORD"] %>
